blank_issues_enabled: false
contact_links:
    - name: File a bug with the Prism Templates
      url: https://github.com/PrismLibrary/Prism.Templates/issues/new/choose
      about: Issues related to the Prism Templates should be filed in the Prism.Templates repo
    - name: Ask a Question
      url: https://github.com/PrismLibrary/Prism/discussions/category_choices
      about: Please ask and answer questions for Prism here.
    - name: Read the Docs
      url: https://prismlibrary.com/docs
      about: Be sure you've read the docs!
    - name: Report missing docs
      url: https://github.com/PrismLibrary/Prism-Documentation/issues/new
      about: Did we miss docs on something? Let us know here!
